name: neuralnet-ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  cleanup-before:
    uses: ./.github/workflows/_cleanup.yml
    with:
      when: "before"

  test-neuralnet:
    needs: cleanup-before
    name: test-neuralnet - ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install pufferlib
        run: |
          pip install -e .[cpu] --no-cache-dir
        env:
          TMPDIR: ${{ runner.temp }}/build
          PIP_NO_CACHE_DIR: 1

      - name: Compile C extensions
        run: python setup.py build_ext --inplace --force

      - name: Run render test
        run: python tests/test_drivenet.py
        timeout-minutes: 15
